# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:bookworm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Install depdencies
        run: |
          apt update && apt upgrade -y
          apt install git nasm bc autoconf automake texinfo flex bison gawk build-essential unzip wget zip less zlib1g-dev libzstd-dev xorriso libtool gcc-multilib python3 attr ncurses-dev pkg-config autopoint genisoimage -y
          git clone https://github.com/haiku/buildtools --depth=1
          cd buildtools
          cd jam 
          make -j$(nproc) 
          ./jam0 install 
          cd ../../

      - name: Bootstrap Haiku
        run: |
          git clone https://github.com/haiku/haiku
          git clone https://github.com/haikuports/haikuporter
          git clone https://github.com/Fancy2209/haikuports.cross
          git clone https://github.com/haikuports/haikuports
          
          cd haiku && mkdir generated.ppc && cd generated.ppc
          ../configure -j$(nproc) --cross-tools-source ../../buildtools --build-cross-tools ppc --bootstrap ../../haikuporter/haikuporter ../../haikuports.cross ../../haikuports
          PATH=/usr/local/bin:$PATH /usr/local/bin/jam -q -sHAIKU_PORTER_CONCURRENT_JOBS=$(nproc) @bootstrap-raw 
          PATH=/usr/local/bin:$PATH /usr/local/bin/jam -q @bootstrap-raw haiku-boot-cd.iso

      - uses: actions/upload-artifact@v4
        with:
          name: HaikuPPC
          path: |
            haiku-bootstrap.image
            haiku-boot-cd.iso
